baseURL = "https://musing-pike-341289.netlify.app/"
languageCode = "en-us"
theme = "hyde"
title = "Action Couch Life"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = true
theme = "hyde"
themeColor = "theme-base-08"
